[program:php-fpm]
command=php-fpm8.3 -F
user=www-data
autostart=true
autorestart=true
stderr_logfile=/var/log/php-fpm.error.log
stdout_logfile=/var/log/php-fpm.stdout.log

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx.error.log
stdout_logfile=/var/log/nginx.stdout.log
